import Head from 'next/head'
import { UncontrolledCarousel, Row, Col } from 'reactstrap'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>I-Drive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=''>
        <h1>iDrive</h1>
      </div>
    </div>
  )
}
